name: BE CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::601525366310:role/github-actions-esrevedoc-be
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t 601525366310.dkr.ecr.eu-north-1.amazonaws.com/esrevedoc-be:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            601525366310.dkr.ecr.eu-north-1.amazonaws.com/esrevedoc-be:${{ github.sha }}
